### ISSUE TITLE
Read response error, please try again

### ISSUE THREAD

**Issue by adumont** [HuskyLens/HUSKYLENSPython#8]
When creating the HuskyLensLibrary() object (via serial), I always get:

```
Read response error, please try again
Read response error, please try again
Read response error, please try again
```
At the same time the HL screen becomes all  black, and won't recover (until I unplug from USB).

I have checked the USB port in the HuskyLensLibrary call, and it is the correct one. I have also forced SERIAL 9600 in the HL settings, as well as in my code, but no luck.

How can I get more info of the error?

BTW, I can see that if I try to connect to the same port via Putty, or Gtkterm, as soon as the usb port is opened, the screen on the Huskylens gets black. is it normal?

I'm using firmware 0.4.9Class.

**Comment by adumont** [comment]
Hum... I am just thinking I was connecting the HL to the computer via the USB cable, and I should probably connect (over USB) using an FTDI board (USB to serial)...

Nevermind, I'll try that and see how that goes.

**Comment by HaydarJawad** [comment]
Hi Mate, did you manage to sort the above in HL issue  ? I am getting same error in windows 10. Using Python code Thank you .

**Comment by adumont** [comment]
If you plug the HL via USB to the computer you are not talking to it over serial. In order to talk serial to it, you need to connect a USB FTDI adapter to the computer and wire its serial pins to the HL serial pins. That way you can talk serial (from Python on the computer for example) to the HL.

**Comment by HaydarJawad** [comment]
Thank you mate, I actually managed to get working on USB, i upgraded the firmware to the latest , and now i can do alerts using face recognition using python . Latest firmware is 0.5.3. 
by the way i love your projects very interesting the single board  computer using it  took me back to my degree days in the 1980s using the  6502  series. great to see 65C02s  as a further development by WDC.  All the  best and thank you again 

https://www.youtube.com/watch?v=mnk06meRZ3U&t=151s
